android:
  platformName: "Android"
  automationName: "uiautomator2"
  deviceName: "emulator-5554"
  platformVersion": "15"
  app: "/Users/mandy/PycharmProjects/myobservatory_test/assets/myobservatory-5-13-1.apk"
  appPackage": "hko.MyObservatory_v1_0"
  appActivity": "hko.homepage3.HomepageActivity"
ios:
  #todo
